#!/usr/bin/env node

import { createInterface } from 'node:readline';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { exec } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CONFIG_PATH = join(ROOT, 'config.js');
const CONFIG_EXAMPLE = join(ROOT, 'config.example.js');

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

function openUrl(url) {
  const cmd =
    process.platform === 'darwin' ? 'open' :
    process.platform === 'win32' ? 'start' : 'xdg-open';
  exec(`${cmd} "${url}"`);
}

const AMBER = '\x1b[33m';
const DIM = '\x1b[2m';
const BOLD = '\x1b[1m';
const RESET = '\x1b[0m';
const GREEN = '\x1b[32m';
const RED = '\x1b[31m';

function heading(text) {
  console.log(`\n${AMBER}${BOLD}${text}${RESET}`);
}

function dim(text) {
  console.log(`${DIM}${text}${RESET}`);
}

console.log(`
${AMBER}  ʕ·ᴥ·ʔ${RESET}
${AMBER}${BOLD}  BAREmail setup${RESET}
${DIM}  ~3 minutes · zero cost · just needs a google account${RESET}
`);

if (existsSync(CONFIG_PATH)) {
  const contents = readFileSync(CONFIG_PATH, 'utf8');
  if (!contents.includes('YOUR_CLIENT_ID')) {
    const answer = await ask(`${DIM}config.js already exists with credentials. overwrite? (y/N): ${RESET}`);
    if (answer.toLowerCase() !== 'y') {
      console.log(`${GREEN}✓ keeping existing config.js${RESET}`);
      rl.close();
      process.exit(0);
    }
  }
}

// Step 1
heading('step 1/4 — create a google cloud project');
dim('opening google cloud console...');
openUrl('https://console.cloud.google.com/projectcreate');
console.log('  create a new project (name it anything, e.g. "baremail").');
console.log('  if you already have a project, skip this.');
await ask(`\n${DIM}  press enter when done...${RESET}`);

// Step 2
heading('step 2/4 — enable the gmail API');
dim('opening gmail API page...');
openUrl('https://console.cloud.google.com/apis/library/gmail.googleapis.com');
console.log('  select your project from the dropdown, then click "enable".');
await ask(`\n${DIM}  press enter when done...${RESET}`);

// Step 3
heading('step 3/4 — configure OAuth consent screen');
dim('opening consent screen settings...');
openUrl('https://console.cloud.google.com/apis/credentials/consent');
console.log('  1. user type: external → create');
console.log('  2. app name: BAREmail (or anything)');
console.log('  3. support email & developer contact: your email');
console.log('  4. save and continue through scopes (no changes)');
console.log(`  5. test users: ${BOLD}add your gmail address${RESET}`);
console.log('  6. save and continue → back to dashboard');
await ask(`\n${DIM}  press enter when done...${RESET}`);

// Step 4
heading('step 4/4 — create OAuth credentials');
dim('opening credentials page...');
openUrl('https://console.cloud.google.com/apis/credentials/oauthclient');
console.log('  1. application type: web application');
console.log('  2. name: BAREmail (or anything)');
console.log('  3. authorized javascript origins: http://localhost:3000');
console.log('  4. authorized redirect URIs: http://localhost:3000');
console.log('  5. click create');
console.log('');

const clientId = await ask(`${AMBER}  paste your client ID: ${RESET}`);
if (!clientId.trim() || !clientId.includes('.apps.googleusercontent.com')) {
  console.log(`${RED}  ✗ that doesn't look like a valid client ID${RESET}`);
  console.log(`${DIM}  it should end with .apps.googleusercontent.com${RESET}`);
  rl.close();
  process.exit(1);
}

const clientSecret = await ask(`${AMBER}  paste your client secret (or press enter to skip): ${RESET}`);

// Write config
const configContent = `// BareMail Configuration — generated by npm run setup
window.BAREMAIL_CONFIG = {
  GOOGLE_CLIENT_ID: '${clientId.trim()}',
  GOOGLE_CLIENT_SECRET: '${clientSecret.trim() || ''}',
  GOOGLE_REDIRECT_URI: window.location.origin,
};
`;

writeFileSync(CONFIG_PATH, configContent);
console.log(`\n${GREEN}  ✓ config.js written${RESET}`);
console.log(`\n${AMBER}${BOLD}  ʕ·ᴥ·ʔ  all done!${RESET}`);
console.log(`${DIM}  run ${RESET}npm start${DIM} and open http://localhost:3000${RESET}\n`);

rl.close();
